insert into cars (brand, model, type, year, engine, fuel, price, image) values ('Nissan', 'GT-R', 'SUV', 2013, 'Electric', 'ethanol', 150, 'http://dummyimage.com/152x100.png/ff4444/ffffff');
insert into cars (brand, model, type, year, engine, fuel, price, image) values ('Maybach', 'Landaulet', 'coupe', 2010, 'V6', 'ethanol', 100, 'http://dummyimage.com/104x100.png/dddddd/000000');
insert into cars (brand, model, type, year, engine, fuel, price, image) values ('Jeep', 'Wrangler', 'coupe', 2009, 'Rotary', 'ethanol', 120, 'http://dummyimage.com/104x100.png/cc0000/ffffff');
insert into cars (brand, model, type, year, engine, fuel, price, image) values ('Buick', 'Riviera', 'SUV', 1997, 'V8', 'propane', 150, 'http://dummyimage.com/229x100.png/ff4444/ffffff');
insert into cars (brand, model, type, year, engine, fuel, price, image) values ('Cadillac', 'Eldorado', 'crossover', 2000, 'V8', 'electric', 90, 'http://dummyimage.com/239x100.png/cc0000/ffffff');
insert into cars (brand, model, type, year, engine, fuel, price, image) values ('BMW', '8 Series', 'crossover', 1996, 'Hybrid', 'diesel', 150, 'http://dummyimage.com/218x100.png/cc0000/ffffff');
insert into cars (brand, model, type, year, engine, fuel, price, image) values ('Pontiac', 'Grand Am', 'crossover', 1991, 'V8', 'ethanol', 100, 'http://dummyimage.com/156x100.png/ff4444/ffffff');
insert into cars (brand, model, type, year, engine, fuel, price, image) values ('Porsche', 'Boxster', 'minivan', 2005, 'V8', 'natural gas', 120, 'http://dummyimage.com/117x100.png/cc0000/ffffff');
insert into cars (brand, model, type, year, engine, fuel, price, image) values ('Toyota', 'Avalon', 'hatchback', 1995, 'Wankel', 'biofuel', 130, 'http://dummyimage.com/188x100.png/5fa2dd/ffffff');
insert into cars (brand, model, type, year, engine, fuel, price, image) values ('Buick', 'Skylark', 'coupe', 1987, 'V6', 'natural gas', 130, 'http://dummyimage.com/225x100.png/cc0000/ffffff');
